// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

error ALREADY_INITIALIZED();
error NOT_OWNER();
error ADDRESS_NOT_GRANTED_YIELD_ACCESS();
error INVALID_INDEX();
error TOKEN_ALLOWANCE();
error DEPOSIT_FAILED();
error INSUFFICIENT_BALANCE();
error TOKEN_NOT_PERMITTED();
error WITHDRAW_FAILED();
error NOT_ENOUGH_YIELD();
error CALLER_MUST_BE_DESTINATION();
error ALREADY_SET();
error NOT_PERMITTED_AMOUNT();
error ROUTER_ACTIVE();
error ROUTER_LOCKED();
error ROUTER_NOT_ACTIVE();
error DESTINATION_ADDRESS_NOT_PERMMITTED();
error ROUTER_DESTIONATION_NOT_SET();
error ROUTER_NOT_LOCKED();
error NOT_FACTORY_OWNER();
error ROUTER_MUST_BE_ACTIVE_TO_LOCK();
error ACCESS_ALREADY_GRANTED();
error ACCESS_ALREADY_NOT_GRANTED();
error NOT_AUTHORIZED();
error INPUT_MUST_BE_IN_WAD_UNITS();
